import { Birds } from './attack-birds'

export enum difficultyEnum {
  EASY,
  MEDIUM,
  HARD,
}

export const PARTS = {
  [difficultyEnum.EASY]: {
    platform: 'platform' as const,
    horizontalLine: 'horizontalLine' as const,
    diamondCloud: 'diamondCloud' as const,
    downSlope: 'downSlope' as const,
    downParable: 'downParable' as const,
    upSlope: 'upSlope' as const,
    upParable: 'upParable' as const,
    zigZag: 'zigZag' as const,
    sineCurve: 'sineCurve' as const,
    bigSine: 'bigSine' as const,
    loop: 'loop' as const,
    greatDiamond: 'greatDiamond' as const,
    smallDiamond: 'smallDiamond' as const,
    highYieldLoop: 'highYieldLoop' as const,
    triangle: 'triangle' as const,
    highYieldTriangle: 'highYieldTriangle' as const,
  },
  [difficultyEnum.MEDIUM]: {
    seagullLoop: 'seagullLoop' as const,
  },
  [difficultyEnum.HARD]: {
    falcon: 'falcon' as const,
    crow: 'crow' as const,
    dualCrows: 'dualCrows' as const,
    bat: 'bat' as const,
    tripleBats: 'tripleBats' as const,
    duck: 'duck' as const,
    dualDucks: 'dualDucks' as const,
    quadDucks: 'quadDucks' as const,
    seagull: 'seagull' as const,
    glasses: 'glasses' as const,
    thunder: 'thunder' as const,
  },
}

export type TrackPart = {
  x: number
  y: number
} & (
  | {
      type: 'attackBird'
      graphicType: 'attackBird'
      animation: Birds
    }
  | {
      type: 'diamond'
      animation: 'cycle'
      graphicType: 'sprite'
    }
  | {
      type: 'greatDiamond'
      animation: 'greatCycle'
      graphicType: 'sprite'
    }
  | {
      type: 'thunderCloud'
      graphicType: 'thunderCloud'
    }
)

export const trackParts: {
  [keyX in difficultyEnum]: {
    [key in keyof typeof PARTS[keyX]]: TrackPart[]
  }
} = {
  [difficultyEnum.EASY]: {
    [PARTS[difficultyEnum.EASY].platform]: [
      {
        x: 0,
        y: 150,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 30,
        y: 180,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 30,
        y: 120,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 50,
        y: 150,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 70,
        y: 120,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 70,
        y: 180,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: 150,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1000,
        y: 130,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1030,
        y: 160,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1030,
        y: 100,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1050,
        y: 130,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1070,
        y: 100,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1070,
        y: 160,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1100,
        y: 130,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2000,
        y: 110,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2030,
        y: 140,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2030,
        y: 80,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2050,
        y: 110,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2070,
        y: 80,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2070,
        y: 140,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2100,
        y: 110,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2000,
        y: 110,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2030,
        y: 140,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2030,
        y: 80,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2050,
        y: 110,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2070,
        y: 80,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2070,
        y: 140,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2100,
        y: 110,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 4000,
        y: 20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 4030,
        y: 50,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 4030,
        y: -10,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 4050,
        y: 20,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 4070,
        y: -10,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 4070,
        y: 50,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 4100,
        y: 20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].highYieldLoop]: [
      {
        x: 300,
        y: 680,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 400,
        y: 580,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 500,
        y: 480,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 600,
        y: 380,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 700,
        y: 280,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 800,
        y: 180,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 900,
        y: 80,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,

      {
        x: 1062.25701405,
        y: -6.52635236,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1125.9907573,
        y: -31.33121883,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1269.7326906,
        y: -76.08854442,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1350.9905274,
        y: -196.6914816,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1418.2035123,
        y: -267.667282,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1456.2628025,
        y: -342.6312799,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1462.9751187,
        y: -415.1770559,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1433.5561625,
        y: -478.6007669,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1386.002438,
        y: -516.4105943,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1329.1994816,
        y: -528.3956859,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1276.2562051,
        y: -513.2310894,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1237.8197927,
        y: -473.157281,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1225.2364304,
        y: -411.9219154,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1244.7922799,
        y: -339.7600216,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1296.2755166,
        y: -274.1601402,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1372.2007193,
        y: -215.620014,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1469.3304597,
        y: -166.6490658,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1590.8224944,
        y: -120.9453239,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1657.9293147,
        y: -107.6224837,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1724.7446863,
        y: -92.2939771,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1791.4098309,
        y: -75.03864139,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1856.1211905,
        y: -56.01061641,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].triangle]: [
      {
        x: 500,
        y: 240,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 500,
        y: -360,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 800,
        y: 140,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 800,
        y: -260,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1200,
        y: 40,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1200,
        y: -160,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1500,
        y: -60,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].highYieldTriangle]: [
      {
        x: 1856.1211905,
        y: -56.01061641,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1100,
        y: 150,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1100,
        y: -450,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1400,
        y: 50,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1400,
        y: -350,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1700,
        y: -50,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1700,
        y: -250,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2000,
        y: -150,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2030,
        y: -120,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2030,
        y: -180,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2050,
        y: -150,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2070,
        y: -180,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2070,
        y: -120,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2100,
        y: -150,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].horizontalLine]: [
      {
        x: 50,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 150,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 200,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 250,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 300,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].diamondCloud]: [
      {
        x: 0,
        y: -50,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 50,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 0,
        y: 50,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: -50,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: 50,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 150,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].downSlope]: [
      {
        x: 0,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 50,
        y: 20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: 40,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 150,
        y: 60,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 200,
        y: 80,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 250,
        y: 100,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].downParable]: [
      {
        x: 50,
        y: 2.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: 10,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 150,
        y: 22.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 200,
        y: 40,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 250,
        y: 62.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 300,
        y: 90,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 350,
        y: 122.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 400,
        y: 160,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 450,
        y: 202.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].upSlope]: [
      {
        x: 0,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 50,
        y: -20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: -40,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 150,
        y: -60,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 200,
        y: -80,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 250,
        y: -100,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].upParable]: [
      {
        x: 50,
        y: -2.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: -10,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 150,
        y: -22.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 200,
        y: -40,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 250,
        y: -62.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 300,
        y: -90,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 350,
        y: -122.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 400,
        y: -160,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 450,
        y: -202.5,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].zigZag]: [
      {
        x: 100,
        y: -20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 200,
        y: 20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 300,
        y: -20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 400,
        y: 20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 500,
        y: -20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 600,
        y: 20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 700,
        y: -20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 800,
        y: 20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1000,
        y: -20,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].sineCurve]: [
      {
        x: 0,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 50,
        y: 15.443276,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 100,
        y: 29.37637629,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 150,
        y: 40.43680303,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 200,
        y: 47.54297303,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 250,
        y: 49.99998415,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 300,
        y: 47.56756881,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 350,
        y: 40.48358941,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 400,
        y: 29.4407781,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 450,
        y: 15.51899548,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 500,
        y: 0.079632646,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 550,
        y: -15.36751735,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 600,
        y: -29.31189996,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 650,
        y: -40.38991407,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 700,
        y: -47.51825664,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 750,
        y: -49.99985732,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 800,
        y: -47.59204394,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 850,
        y: -40.53027311,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 900,
        y: -29.50510523,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 950,
        y: -15.5946756,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].bigSine]: [
      {
        x: 0,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 150,
        y: 46.32982801,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 300,
        y: 88.12912886,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 450,
        y: 121.3104091,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 600,
        y: 142.6289191,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 750,
        y: 149.9999524,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 900,
        y: 142.7027064,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1050,
        y: 121.4507682,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1200,
        y: 88.3223343,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1350,
        y: 46.55698645,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1500,
        y: 0.238897937,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1650,
        y: -46.10255206,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1800,
        y: -87.93569988,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 1950,
        y: -121.1697422,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2100,
        y: -142.5547699,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2250,
        y: -149.999572,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2400,
        y: -142.7761318,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2550,
        y: -121.5908193,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2700,
        y: -88.5153157,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 2850,
        y: -46.78402679,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    // /looop
    [PARTS[difficultyEnum.EASY].loop]: [
      {
        x: 62.25701405,
        y: -26.52635236,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 125.9907573,
        y: -51.33121883,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 269.7326906,
        y: -96.08854442,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 350.9905274,
        y: -216.6914816,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 418.2035123,
        y: -287.667282,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 456.2628025,
        y: -362.6312799,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 462.9751187,
        y: -435.1770559,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 433.5561625,
        y: -498.6007669,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 386.002438,
        y: -536.4105943,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 329.1994816,
        y: -548.3956859,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 276.2562051,
        y: -533.2310894,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 237.8197927,
        y: -493.157281,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 225.2364304,
        y: -431.9219154,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 244.7922799,
        y: -359.7600216,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 296.2755166,
        y: -294.1601402,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 372.2007193,
        y: -235.620014,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 469.3304597,
        y: -186.6490658,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 590.8224944,
        y: -140.9453239,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 657.9293147,
        y: -127.6224837,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 724.7446863,
        y: -112.2939771,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 791.4098309,
        y: -95.03864139,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 856.1211905,
        y: -76.01061641,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    // great diamond
    [PARTS[difficultyEnum.EASY].greatDiamond]: [
      {
        x: 0,
        y: 0,
        type: 'greatDiamond',
        animation: 'greatCycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.EASY].smallDiamond]: [
      {
        x: 0,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
  },
  [difficultyEnum.MEDIUM]: {
    // /looop w seagull
    [PARTS[difficultyEnum.MEDIUM].seagullLoop]: [
      {
        x: 0,
        y: 0,
        type: 'attackBird',
        animation: 'seagull',
        graphicType: 'attackBird',
      } as TrackPart,
      {
        x: 0,
        y: 0,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 62.25701405,
        y: -26.52635236,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 125.9907573,
        y: -51.33121883,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 269.7326906,
        y: -96.08854442,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 350.9905274,
        y: -216.6914816,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 418.2035123,
        y: -287.667282,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 456.2628025,
        y: -362.6312799,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 462.9751187,
        y: -435.1770559,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 433.5561625,
        y: -498.6007669,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 386.002438,
        y: -536.4105943,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 329.1994816,
        y: -548.3956859,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 276.2562051,
        y: -533.2310894,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 237.8197927,
        y: -493.157281,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 225.2364304,
        y: -431.9219154,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 244.7922799,
        y: -359.7600216,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 296.2755166,
        y: -294.1601402,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 372.2007193,
        y: -235.620014,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 469.3304597,
        y: -186.6490658,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 590.8224944,
        y: -140.9453239,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 657.9293147,
        y: -127.6224837,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 724.7446863,
        y: -112.2939771,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 791.4098309,
        y: -95.03864139,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
      {
        x: 856.1211905,
        y: -76.01061641,
        type: 'diamond',
        animation: 'cycle',
        graphicType: 'sprite',
      } as TrackPart,
    ],
  },
  [difficultyEnum.HARD]: {
    [PARTS[difficultyEnum.HARD].falcon]: [
      {
        x: -500,
        y: -400,
        type: 'attackBird',
        animation: 'falcon',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].crow]: [
      {
        x: 0,
        y: 0,
        type: 'attackBird',
        animation: 'crow',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].dualCrows]: [
      {
        x: 10,
        y: -200,
        type: 'attackBird',
        animation: 'crow',
        graphicType: 'attackBird',
      } as TrackPart,
      {
        x: 200,
        y: -400,
        type: 'attackBird',
        animation: 'crow',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].bat]: [
      {
        x: 0,
        y: 0,
        type: 'attackBird',
        animation: 'bat',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].tripleBats]: [
      {
        x: -700,
        y: 400,
        type: 'attackBird',
        animation: 'bat',
        graphicType: 'attackBird',
      } as TrackPart,
      {
        x: -800,
        y: 500,
        type: 'attackBird',
        animation: 'bat',
        graphicType: 'attackBird',
      } as TrackPart,
      {
        x: -900,
        y: 700,
        type: 'attackBird',
        animation: 'bat',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].duck]: [
      {
        x: 0,
        y: -200,
        type: 'attackBird',
        animation: 'duck',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].dualDucks]: [
      {
        x: 0,
        y: -200,
        type: 'attackBird',
        animation: 'duck',
        graphicType: 'attackBird',
      } as TrackPart,
      {
        x: 0,
        y: -400,
        type: 'attackBird',
        animation: 'duck',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].quadDucks]: [
      {
        x: 0,
        y: -200,
        type: 'attackBird',
        animation: 'duck',
        graphicType: 'attackBird',
      } as TrackPart,
      {
        x: 0,
        y: -400,
        type: 'attackBird',
        animation: 'duck',
        graphicType: 'attackBird',
      } as TrackPart,
      {
        x: 0,
        y: 200,
        type: 'attackBird',
        animation: 'duck',
        graphicType: 'attackBird',
      } as TrackPart,
      {
        x: 0,
        y: 400,
        type: 'attackBird',
        animation: 'duck',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].seagull]: [
      {
        x: 0,
        y: 0,
        type: 'attackBird',
        animation: 'seagull',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].glasses]: [
      {
        x: 0,
        y: 0,
        type: 'attackBird',
        animation: 'glasses',
        graphicType: 'attackBird',
      } as TrackPart,
    ],
    [PARTS[difficultyEnum.HARD].thunder]: [
      {
        x: 0,
        y: 0,
        type: 'thunderCloud',
        graphicType: 'thunderCloud',
      } as TrackPart,
    ],
  },
}
